baseURL = "https://sakaspar.github.io/blog/"
locale = "en-us"
title = "DotKsp Writings"
theme = "PaperMod"
paginate = 5
enableRobotsTXT = true
[params]
  env = "production"
  title = "DotKsp Writings"
  description = "Thoughts on crypto, tech, and building things"
  author = "DotKsp"
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true

[params.homeInfoParams]
  Title = "DotKsp Writings"
  Content = "The map they don't hand out."

[[params.socialIcons]]
  name = "x"
  url = "https://x.com/Kasper_0927"

[params.profileMode]
  enabled = false
  title = "DotKsp Writings"
  subtitle = "The map they don't hand out."
  imageUrl = "images/avatar.jpg"
  imageWidth = 120
  imageHeight = 120
  imageTitle = "DotKsp"


[params.assets]
  disableHLJS = true

[[menu.main]]
  identifier = "posts"
  name = "Posts"
  url = "/posts/"
  weight = 10

[[menu.main]]
  identifier = "tags"
  name = "Tags"
  url = "/tags/"
  weight = 20